// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "../src/Hash.res.mjs";
import * as PersistentHashMap from "../src/PersistentHashMap.res.mjs";

describe("Hash — primitive hashing", () => {
  test("equal primitives hash to the same value", () => {
    expect(Hash.hash(42)).toBe(Hash.hash(42));
    expect(Hash.hash("hello")).toBe(Hash.hash("hello"));
    expect(Hash.hash(true)).toBe(Hash.hash(true));
    expect(Hash.hash(false)).toBe(Hash.hash(false));
    expect(Hash.hash(true) === Hash.hash(false)).toBe(false);
  });
  test("integer-valued floats and ints hash equally", () => {
    expect(Hash.hash(3)).toBe(Hash.hash(3.0));
  });
  test("non-integer floats use the IEEE-754 hash path", () => {
    expect(Hash.hash(3.14)).toBe(Hash.hash(3.14));
    expect(Hash.hash(3.14) === Hash.hash(2.71)).toBe(false);
  });
  test("equals is === for primitives", () => {
    expect(Hash.equals(1, 1)).toBe(true);
    expect(Hash.equals("x", "x")).toBe(true);
    expect(Hash.equals(1, 2)).toBe(false);
    expect(Hash.equals("x", "y")).toBe(false);
  });
});

describe("Hash — object identity (regression)", () => {
  test("two structurally-equal objects are NOT equal (identity semantics)", () => {
    let a = {
      x: 1,
      y: 2
    };
    let b = {
      x: 1,
      y: 2
    };
    expect(Hash.equals(a, b)).toBe(false);
    expect(Hash.equals(a, a)).toBe(true);
  });
  test("the same object hashes to the same value across calls", () => {
    let a = {
      x: 1
    };
    let h1 = Hash.hash(a);
    let h2 = Hash.hash(a);
    expect(h1).toBe(h2);
  });
  test("distinct objects (overwhelmingly) hash to different values", () => {
    let a = {
      x: 1
    };
    let b = {
      x: 1
    };
    expect(Hash.hash(a) === Hash.hash(b)).toBe(false);
  });
  test("cyclic objects do not throw (regression: JSON.stringify would throw)", () => {
    let cyclic = {};
    cyclic["self"] = cyclic;
    let h = Hash.hash(cyclic);
    expect(h === Hash.hash(cyclic)).toBe(true);
  });
  test("functions can be used as keys without throwing", () => {
    let f = () => 1;
    let g = () => 1;
    let h1 = Hash.hash(f);
    expect(h1).toBe(Hash.hash(f));
    expect(Hash.equals(f, g)).toBe(false);
    expect(Hash.equals(f, f)).toBe(true);
  });
  test("null hashes to 0 and equals itself", () => {
    expect(Hash.hash(null)).toBe(0);
    expect(Hash.equals(null, null)).toBe(true);
  });
});

describe("PersistentHashMap with object keys uses identity", () => {
  test("the same object key round-trips", () => {
    let k = {
      id: 1
    };
    let m = PersistentHashMap.set(PersistentHashMap.make(), k, "v");
    expect(PersistentHashMap.getExn(m, k)).toBe("v");
    expect(PersistentHashMap.has(m, k)).toBe(true);
  });
  test("structurally-equal but distinct objects are different keys", () => {
    let k1 = {
      id: 1
    };
    let k2 = {
      id: 1
    };
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), k1, "a"), k2, "b");
    expect(PersistentHashMap.size(m)).toBe(2);
    expect(PersistentHashMap.getExn(m, k1)).toBe("a");
    expect(PersistentHashMap.getExn(m, k2)).toBe("b");
  });
});

/*  Not a pure module */
