// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as PersistentVector from "../src/PersistentVector.res.mjs";

describe("PersistentVector — basics", () => {
  test("empty vector has size 0", () => {
    expect(PersistentVector.size(PersistentVector.make())).toBe(0);
  });
  test("push/get round-trip for small vectors", () => {
    let v = PersistentVector.fromArray([
      1,
      2,
      3,
      4,
      5
    ]);
    expect(PersistentVector.size(v)).toBe(5);
    expect(PersistentVector.getExn(v, 0)).toBe(1);
    expect(PersistentVector.getExn(v, 4)).toBe(5);
    expect(PersistentVector.get(v, 5)).toEqual(undefined);
  });
  test("set returns a new vector and preserves the old", () => {
    let v = PersistentVector.fromArray([
      10,
      20,
      30
    ]);
    let w = PersistentVector.set(v, 1, 99);
    expect(PersistentVector.getExn(v, 1)).toBe(20);
    expect(PersistentVector.getExn(w, 1)).toBe(99);
    expect(PersistentVector.size(w)).toBe(3);
  });
  test("set at index == size acts like push (conj)", () => {
    let v = PersistentVector.fromArray([
      1,
      2
    ]);
    let w = PersistentVector.set(v, 2, 3);
    expect(PersistentVector.toArray(w)).toEqual([
      1,
      2,
      3
    ]);
  });
  test("pop removes the last element", () => {
    let v = PersistentVector.fromArray([
      1,
      2,
      3
    ]);
    let w = PersistentVector.pop(v);
    expect(PersistentVector.size(w)).toBe(2);
    expect(PersistentVector.toArray(w)).toEqual([
      1,
      2
    ]);
  });
  test("toArray round-trip on a 1000-element vector (crosses tail boundary)", () => {
    let arr = Core__Array.fromInitializer(1000, i => i);
    let v = PersistentVector.fromArray(arr);
    expect(PersistentVector.size(v)).toBe(1000);
    expect(PersistentVector.toArray(v)).toEqual(arr);
  });
  test("structural sharing: setting one element does not mutate the original", () => {
    let v = PersistentVector.fromArray(Core__Array.fromInitializer(200, i => i));
    let w = PersistentVector.set(v, 100, -1);
    expect(PersistentVector.getExn(v, 100)).toBe(100);
    expect(PersistentVector.getExn(w, 100)).toBe(-1);
  });
  test("push/pop stress crosses multiple trie levels (10 000 elements)", () => {
    let v = PersistentVector.make();
    for (let i = 0; i <= 9999; ++i) {
      v = PersistentVector.push(v, i);
    }
    expect(PersistentVector.size(v)).toBe(10000);
    for (let i$1 = 0; i$1 <= 9999; ++i$1) {
      expect(PersistentVector.getExn(v, i$1)).toBe(i$1);
    }
    for (let _for = 1; _for <= 10000; ++_for) {
      v = PersistentVector.pop(v);
    }
    expect(PersistentVector.size(v)).toBe(0);
  });
  test("forEach / reduce / map / filter", () => {
    let v = PersistentVector.fromArray([
      1,
      2,
      3,
      4,
      5
    ]);
    let sum = PersistentVector.reduce(v, 0, (acc, x) => acc + x | 0);
    expect(sum).toBe(15);
    expect(PersistentVector.toArray(PersistentVector.map(v, x => (x << 1)))).toEqual([
      2,
      4,
      6,
      8,
      10
    ]);
    expect(PersistentVector.toArray(PersistentVector.filter(v, x => x % 2 === 0))).toEqual([
      2,
      4
    ]);
  });
  test("iterator yields every element exactly once", () => {
    let v = PersistentVector.fromArray(Core__Array.fromInitializer(100, i => i));
    let it = PersistentVector.iterator(v);
    let seen = [];
    let go = true;
    while (go) {
      let step = it.next();
      if (step.done) {
        go = false;
      } else {
        let x = step.value;
        if (x !== undefined) {
          seen.push(x);
        }
      }
    };
    expect(seen).toEqual(Core__Array.fromInitializer(100, i => i));
  });
});

describe("PersistentVector — transients", () => {
  test("transient pushMut + persistent matches the persistent path", () => {
    let built = PersistentVector.withTransient(PersistentVector.make(), t => {
      let cur = t;
      for (let i = 0; i <= 4999; ++i) {
        cur = PersistentVector.pushMut(cur, i);
      }
      return cur;
    });
    expect(PersistentVector.size(built)).toBe(5000);
    [
      0,
      31,
      32,
      33,
      1023,
      1024,
      1025,
      4999
    ].forEach(i => {
      expect(PersistentVector.getExn(built, i)).toBe(i);
    });
  });
  test("transient setMut updates in place", () => {
    let v = PersistentVector.fromArray(Core__Array.fromInitializer(100, i => i));
    let w = PersistentVector.withTransient(v, t => {
      let cur = t;
      for (let i = 0; i <= 99; ++i) {
        cur = PersistentVector.setMut(cur, i, i * 10 | 0);
      }
      return cur;
    });
    expect(PersistentVector.getExn(v, 50)).toBe(50);
    expect(PersistentVector.getExn(w, 50)).toBe(500);
  });
  test("using a transient after persistent! throws", () => {
    let t = PersistentVector.asTransient(PersistentVector.fromArray([
      1,
      2,
      3
    ]));
    PersistentVector.persistent(t);
    expect(() => {
      PersistentVector.pushMut(t, 4);
    }).toThrow();
  });
});

let V;

export {
  V,
}
/*  Not a pure module */
