// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PersistentQueue from "../src/PersistentQueue.res.mjs";

describe("PersistentQueue — basics", () => {
  test("empty queue has size 0 and isEmpty true", () => {
    let q = PersistentQueue.make();
    expect(PersistentQueue.size(q)).toBe(0);
    expect(PersistentQueue.isEmpty(q)).toBe(true);
  });
  test("enqueue/peek/dequeue round-trip", () => {
    let q = PersistentQueue.enqueue(PersistentQueue.enqueue(PersistentQueue.enqueue(PersistentQueue.make(), 1), 2), 3);
    expect(PersistentQueue.size(q)).toBe(3);
    expect(PersistentQueue.peek(q)).toEqual(1);
    let match = Core__Option.getExn(PersistentQueue.dequeue(q), undefined);
    let q2 = match[1];
    expect(match[0]).toBe(1);
    expect(PersistentQueue.size(q2)).toBe(2);
    expect(PersistentQueue.peek(q2)).toEqual(2);
  });
  test("FIFO order preserved across rebalance (N > 1000)", () => {
    let q = PersistentQueue.make();
    for (let i = 0; i <= 999; ++i) {
      q = PersistentQueue.enqueue(q, i);
    }
    let ok = true;
    for (let i$1 = 0; i$1 <= 999; ++i$1) {
      let match = PersistentQueue.dequeue(q);
      if (match !== undefined) {
        if (match[0] !== i$1) {
          ok = false;
        }
        q = match[1];
      } else {
        ok = false;
      }
    }
    expect(ok).toBe(true);
  });
  test("peek on empty returns None", () => {
    expect(PersistentQueue.peek(PersistentQueue.make())).toEqual(undefined);
  });
  test("dequeue on empty returns None", () => {
    expect(PersistentQueue.dequeue(PersistentQueue.make())).toEqual(undefined);
  });
  test("peekExn/dequeueExn throw on empty", () => {
    expect(() => PersistentQueue.peekExn(PersistentQueue.make())).toThrow();
    expect(() => PersistentQueue.dequeueExn(PersistentQueue.make())).toThrow();
  });
  test("toArray preserves FIFO order", () => {
    let q = PersistentQueue.enqueue(PersistentQueue.enqueue(PersistentQueue.enqueue(PersistentQueue.make(), 10), 20), 30);
    expect(PersistentQueue.toArray(q)).toEqual([
      10,
      20,
      30
    ]);
  });
  test("fromArray preserves order", () => {
    let arr = [
      1,
      2,
      3,
      4,
      5
    ];
    let q = PersistentQueue.fromArray(arr);
    expect(PersistentQueue.toArray(q)).toEqual(arr);
  });
  test("structural sharing: dequeue does not mutate original", () => {
    let q = PersistentQueue.enqueue(PersistentQueue.enqueue(PersistentQueue.make(), 1), 2);
    PersistentQueue.dequeue(q);
    expect(PersistentQueue.size(q)).toBe(2);
    expect(PersistentQueue.peek(q)).toEqual(1);
  });
});

let Q;

export {
  Q,
}
/*  Not a pure module */
