// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "../src/Hash.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as PersistentHashMap from "../src/PersistentHashMap.res.mjs";

describe("PersistentHashMap — basics", () => {
  test("empty map has size 0 and missing keys return None", () => {
    let m = PersistentHashMap.make();
    expect(PersistentHashMap.size(m)).toBe(0);
    expect(PersistentHashMap.get(m, "missing")).toEqual(undefined);
    expect(PersistentHashMap.has(m, "missing")).toBe(false);
  });
  test("set / get / has round-trip", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), "a", 1), "b", 2), "c", 3);
    expect(PersistentHashMap.size(m)).toBe(3);
    expect(PersistentHashMap.get(m, "a")).toEqual(1);
    expect(PersistentHashMap.get(m, "b")).toEqual(2);
    expect(PersistentHashMap.get(m, "c")).toEqual(3);
    expect(PersistentHashMap.has(m, "a")).toBe(true);
    expect(PersistentHashMap.has(m, "z")).toBe(false);
  });
  test("setting an existing key replaces, not grows", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), "a", 1), "a", 9);
    expect(PersistentHashMap.size(m)).toBe(1);
    expect(PersistentHashMap.getExn(m, "a")).toBe(9);
  });
  test("structural sharing: removing from a copy does not affect the original", () => {
    let a = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ],
      [
        "c",
        3
      ]
    ]);
    let b = PersistentHashMap.remove(a, "b");
    expect(PersistentHashMap.has(a, "b")).toBe(true);
    expect(PersistentHashMap.has(b, "b")).toBe(false);
    expect(PersistentHashMap.size(a)).toBe(3);
    expect(PersistentHashMap.size(b)).toBe(2);
  });
  test("remove on non-existent key is a no-op (returns same map)", () => {
    let a = PersistentHashMap.fromEntries([[
        "a",
        1
      ]]);
    let b = PersistentHashMap.remove(a, "z");
    expect(PersistentHashMap.size(b)).toBe(1);
    expect(b === a).toBe(true);
  });
  test("large random insert / lookup (10 000 string keys)", () => {
    let m = PersistentHashMap.make();
    for (let i = 0; i <= 9999; ++i) {
      m = PersistentHashMap.set(m, "key-" + i.toString(), i);
    }
    expect(PersistentHashMap.size(m)).toBe(10000);
    for (let i$1 = 0; i$1 <= 9999; ++i$1) {
      expect(PersistentHashMap.getExn(m, "key-" + i$1.toString())).toBe(i$1);
    }
    for (let i$2 = 0; i$2 <= 4999; ++i$2) {
      m = PersistentHashMap.remove(m, "key-" + i$2.toString());
    }
    expect(PersistentHashMap.size(m)).toBe(5000);
    expect(PersistentHashMap.get(m, "key-0")).toEqual(undefined);
    expect(PersistentHashMap.getExn(m, "key-" + (9999).toString())).toBe(9999);
  });
  test("keys/values/entries sizes match", () => {
    let m = PersistentHashMap.fromEntries([
      [
        "x",
        1
      ],
      [
        "y",
        2
      ],
      [
        "z",
        3
      ]
    ]);
    expect(PersistentHashMap.keys(m).length).toBe(3);
    expect(PersistentHashMap.values(m).length).toBe(3);
    expect(PersistentHashMap.entries(m).length).toBe(3);
  });
  test("forEach visits every entry exactly once", () => {
    let m = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ],
      [
        "c",
        3
      ],
      [
        "d",
        4
      ]
    ]);
    let total = {
      contents: 0
    };
    PersistentHashMap.forEach(m, (param, v) => {
      total.contents = total.contents + v | 0;
    });
    expect(total.contents).toBe(10);
  });
  test("iterator yields all entries", () => {
    let pairs = Core__Array.fromInitializer(200, i => [
      "k" + i.toString(),
      i
    ]);
    let m = PersistentHashMap.fromEntries(pairs);
    let it = PersistentHashMap.iterator(m);
    let seen = 0;
    let keep = true;
    while (keep) {
      let step = it.next();
      if (step.done) {
        keep = false;
      } else {
        seen = seen + 1 | 0;
      }
    };
    expect(seen).toBe(200);
  });
  test("merge combines two maps; right wins on conflict", () => {
    let a = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ]
    ]);
    let b = PersistentHashMap.fromEntries([
      [
        "b",
        99
      ],
      [
        "c",
        3
      ]
    ]);
    let m = PersistentHashMap.merge(a, b);
    expect(PersistentHashMap.size(m)).toBe(3);
    expect(PersistentHashMap.getExn(m, "a")).toBe(1);
    expect(PersistentHashMap.getExn(m, "b")).toBe(99);
    expect(PersistentHashMap.getExn(m, "c")).toBe(3);
  });
  test("equals compares structurally", () => {
    let a = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ]
    ]);
    let b = PersistentHashMap.fromEntries([
      [
        "b",
        2
      ],
      [
        "a",
        1
      ]
    ]);
    expect(PersistentHashMap.equals(a, b, (x, y) => x === y)).toBe(true);
    expect(PersistentHashMap.equals(a, PersistentHashMap.set(b, "a", 99), (x, y) => x === y)).toBe(false);
  });
});

describe("PersistentHashMap — collision handling", () => {
  test("two keys with the same hash both round-trip", () => {
    let h1 = Hash.hashString("Aa");
    let h2 = Hash.hashString("BB");
    expect(h1).toBe(h2);
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), "Aa", 1), "BB", 2);
    expect(PersistentHashMap.size(m)).toBe(2);
    expect(PersistentHashMap.getExn(m, "Aa")).toBe(1);
    expect(PersistentHashMap.getExn(m, "BB")).toBe(2);
    let m2 = PersistentHashMap.remove(m, "Aa");
    expect(PersistentHashMap.size(m2)).toBe(1);
    expect(PersistentHashMap.get(m2, "Aa")).toEqual(undefined);
    expect(PersistentHashMap.getExn(m2, "BB")).toBe(2);
  });
  test("colliding and non-colliding keys coexist correctly", () => {
    let keys = [
      "Aa",
      "BB",
      "AaAa"
    ];
    expect(Hash.hashString("Aa")).toBe(Hash.hashString("BB"));
    expect(Hash.hashString("Aa") === Hash.hashString("AaAa")).toBe(false);
    let m = PersistentHashMap.fromEntries(keys.map((k, i) => [
      k,
      i
    ]));
    expect(PersistentHashMap.size(m)).toBe(3);
    keys.forEach((k, i) => {
      expect(PersistentHashMap.getExn(m, k)).toBe(i);
    });
  });
});

describe("PersistentHashMap — null/undefined key distinction", () => {
  test("null and undefined keys are distinct", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), null, 1), undefined, 2);
    expect(PersistentHashMap.size(m)).toBe(2);
    expect(PersistentHashMap.get(m, null)).toEqual(1);
    expect(PersistentHashMap.get(m, undefined)).toEqual(2);
  });
  test("entries preserves the original key (null stays null, undefined stays undefined)", () => {
    let m = PersistentHashMap.set(PersistentHashMap.make(), null, 42);
    let es = PersistentHashMap.entries(m);
    expect(es.length).toBe(1);
    let match = es[0];
    expect(match[0] === null).toBe(true);
    expect(match[1]).toBe(42);
  });
  test("remove null does not remove undefined", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), null, 1), undefined, 2);
    let m2 = PersistentHashMap.remove(m, null);
    expect(PersistentHashMap.has(m2, null)).toBe(false);
    expect(PersistentHashMap.get(m2, undefined)).toEqual(2);
  });
});

describe("PersistentHashMap — transients", () => {
  test("setMut + persistent preserves correctness for 5000 entries", () => {
    let m = PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
      let cur = t;
      for (let i = 0; i <= 4999; ++i) {
        cur = PersistentHashMap.setMut(cur, "k" + i.toString(), i);
      }
      return cur;
    });
    expect(PersistentHashMap.size(m)).toBe(5000);
    for (let i = 0; i <= 4999; ++i) {
      expect(PersistentHashMap.getExn(m, "k" + i.toString())).toBe(i);
    }
  });
  test("transient does not affect original map", () => {
    let original = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ]
    ]);
    let extended = PersistentHashMap.withTransient(original, t => {
      PersistentHashMap.setMut(t, "c", 3);
      PersistentHashMap.setMut(t, "d", 4);
      return t;
    });
    expect(PersistentHashMap.size(original)).toBe(2);
    expect(PersistentHashMap.size(extended)).toBe(4);
    expect(PersistentHashMap.has(original, "c")).toBe(false);
    expect(PersistentHashMap.has(extended, "c")).toBe(true);
  });
  test("using a transient after persistent! throws", () => {
    let t = PersistentHashMap.asTransient(PersistentHashMap.fromEntries([[
        "a",
        1
      ]]));
    PersistentHashMap.persistent(t);
    expect(() => {
      PersistentHashMap.setMut(t, "b", 2);
    }).toThrow();
  });
});

describe("PersistentHashMap — lazy iterator", () => {
  test("iterator yields exactly size elements", () => {
    let m = PersistentHashMap.make();
    for (let i = 0; i <= 999; ++i) {
      m = PersistentHashMap.set(m, i, (i << 1));
    }
    let it = PersistentHashMap.iterator(m);
    let count = 0;
    let step = it.next();
    while (!step.done) {
      count = count + 1 | 0;
      step = it.next();
    };
    expect(count).toBe(1000);
  });
  test("iterator terminates correctly with null/undefined keys", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), null, 0), undefined, 1), "a", 2);
    let it = PersistentHashMap.iterator(m);
    let count = 0;
    let step = it.next();
    while (!step.done) {
      count = count + 1 | 0;
      step = it.next();
    };
    expect(count).toBe(3);
  });
  test("isEmpty returns true for empty map", () => {
    expect(PersistentHashMap.isEmpty(PersistentHashMap.make())).toBe(true);
    expect(PersistentHashMap.isEmpty(PersistentHashMap.set(PersistentHashMap.make(), "a", 1))).toBe(false);
  });
});

describe("PersistentHashMap — map/filter/update", () => {
  test("map transforms all values", () => {
    let m = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ],
      [
        "c",
        3
      ]
    ]);
    let m2 = PersistentHashMap.map(m, v => v * 10 | 0);
    expect(PersistentHashMap.getExn(m2, "a")).toBe(10);
    expect(PersistentHashMap.getExn(m2, "b")).toBe(20);
    expect(PersistentHashMap.size(m2)).toBe(3);
    expect(PersistentHashMap.getExn(m, "a")).toBe(1);
  });
  test("filter keeps only matching entries", () => {
    let m = PersistentHashMap.fromEntries([
      [
        "a",
        1
      ],
      [
        "b",
        2
      ],
      [
        "c",
        3
      ]
    ]);
    let m2 = PersistentHashMap.filter(m, (param, v) => v > 1);
    expect(PersistentHashMap.size(m2)).toBe(2);
    expect(PersistentHashMap.has(m2, "a")).toBe(false);
    expect(PersistentHashMap.has(m2, "b")).toBe(true);
  });
  test("update inserts when key absent", () => {
    let m = PersistentHashMap.make();
    let m2 = PersistentHashMap.update(m, "x", param => 42);
    expect(PersistentHashMap.getExn(m2, "x")).toBe(42);
  });
  test("update modifies existing key", () => {
    let m = PersistentHashMap.fromEntries([[
        "x",
        10
      ]]);
    let m2 = PersistentHashMap.update(m, "x", v => Core__Option.getOr(v, 0) + 5 | 0);
    expect(PersistentHashMap.getExn(m2, "x")).toBe(15);
  });
  test("update removes key when f returns None", () => {
    let m = PersistentHashMap.fromEntries([[
        "x",
        10
      ]]);
    let m2 = PersistentHashMap.update(m, "x", param => {});
    expect(PersistentHashMap.has(m2, "x")).toBe(false);
    expect(PersistentHashMap.size(m2)).toBe(0);
  });
  test("map with null and undefined keys", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), "a", 1), null, 2), undefined, 3);
    let m2 = PersistentHashMap.map(m, v => v * 10 | 0);
    expect(PersistentHashMap.get(m2, "a")).toEqual(10);
    expect(PersistentHashMap.get(m2, null)).toEqual(20);
    expect(PersistentHashMap.get(m2, undefined)).toEqual(30);
  });
  test("filter with null and undefined keys", () => {
    let m = PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.set(PersistentHashMap.make(), "a", 1), null, 2), undefined, 3);
    let m2 = PersistentHashMap.filter(m, (param, v) => v > 1);
    expect(PersistentHashMap.size(m2)).toBe(2);
    expect(PersistentHashMap.get(m2, "a")).toEqual(undefined);
    expect(PersistentHashMap.get(m2, null)).toEqual(2);
    expect(PersistentHashMap.get(m2, undefined)).toEqual(3);
  });
  test("update absent key with f returning None is a no-op", () => {
    let m = PersistentHashMap.make();
    let m2 = PersistentHashMap.update(m, "x", param => {});
    expect(PersistentHashMap.size(m2)).toBe(0);
  });
});

let M;

export {
  M,
}
/*  Not a pure module */
