// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PersistentHashSet from "../src/PersistentHashSet.res.mjs";

describe("PersistentHashSet — basics", () => {
  test("empty set", () => {
    expect(PersistentHashSet.size(PersistentHashSet.make())).toBe(0);
    expect(PersistentHashSet.has(PersistentHashSet.make(), "x")).toBe(false);
  });
  test("add / has / remove", () => {
    let s = PersistentHashSet.add(PersistentHashSet.add(PersistentHashSet.add(PersistentHashSet.make(), "a"), "b"), "a");
    expect(PersistentHashSet.size(s)).toBe(2);
    expect(PersistentHashSet.has(s, "a")).toBe(true);
    expect(PersistentHashSet.has(s, "c")).toBe(false);
    let s2 = PersistentHashSet.remove(s, "a");
    expect(PersistentHashSet.size(s2)).toBe(1);
    expect(PersistentHashSet.has(s2, "a")).toBe(false);
    expect(PersistentHashSet.has(s, "a")).toBe(true);
  });
  test("set operations", () => {
    let a = PersistentHashSet.fromArray([
      "a",
      "b",
      "c",
      "d"
    ]);
    let b = PersistentHashSet.fromArray([
      "c",
      "d",
      "e",
      "f"
    ]);
    expect(PersistentHashSet.size(PersistentHashSet.union(a, b))).toBe(6);
    let inter = PersistentHashSet.intersect(a, b);
    expect(PersistentHashSet.size(inter)).toBe(2);
    expect(PersistentHashSet.has(inter, "c")).toBe(true);
    expect(PersistentHashSet.has(inter, "d")).toBe(true);
    let diff = PersistentHashSet.difference(a, b);
    expect(PersistentHashSet.size(diff)).toBe(2);
    expect(PersistentHashSet.has(diff, "a")).toBe(true);
    expect(PersistentHashSet.has(diff, "c")).toBe(false);
  });
  test("transient batch insert", () => {
    let s = PersistentHashSet.withTransient(PersistentHashSet.make(), t => {
      let cur = t;
      for (let i = 0; i <= 1999; ++i) {
        cur = PersistentHashSet.addMut(cur, "x" + i.toString());
      }
      return cur;
    });
    expect(PersistentHashSet.size(s)).toBe(2000);
    expect(PersistentHashSet.has(s, "x0")).toBe(true);
    expect(PersistentHashSet.has(s, "x1999")).toBe(true);
    expect(PersistentHashSet.has(s, "x2000")).toBe(false);
  });
  test("iterator visits each element once", () => {
    let s = PersistentHashSet.fromArray([
      "a",
      "b",
      "c",
      "d",
      "e"
    ]);
    let it = PersistentHashSet.iterator(s);
    let count = 0;
    let keep = true;
    while (keep) {
      let step = it.next();
      if (step.done) {
        keep = false;
      } else {
        count = count + 1 | 0;
      }
    };
    expect(count).toBe(5);
  });
  test("isEmpty returns true for empty set", () => {
    expect(PersistentHashSet.isEmpty(PersistentHashSet.make())).toBe(true);
    expect(PersistentHashSet.isEmpty(PersistentHashSet.add(PersistentHashSet.make(), 1))).toBe(false);
  });
});

describe("PersistentHashSet — equals/subset/superset/filter/map", () => {
  test("equals returns true for identical content", () => {
    let a = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    let b = PersistentHashSet.fromArray([
      3,
      1,
      2
    ]);
    expect(PersistentHashSet.equals(a, b)).toBe(true);
  });
  test("equals returns false when content differs", () => {
    let a = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    let b = PersistentHashSet.fromArray([
      1,
      2,
      4
    ]);
    expect(PersistentHashSet.equals(a, b)).toBe(false);
    expect(PersistentHashSet.equals(PersistentHashSet.fromArray([
      1,
      2
    ]), PersistentHashSet.fromArray([
      1,
      2,
      3
    ]))).toBe(false);
  });
  test("isSubsetOf", () => {
    let a = PersistentHashSet.fromArray([
      1,
      2
    ]);
    let b = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    expect(PersistentHashSet.isSubsetOf(a, b)).toBe(true);
    expect(PersistentHashSet.isSubsetOf(b, a)).toBe(false);
    expect(PersistentHashSet.isSubsetOf(a, a)).toBe(true);
  });
  test("isSupersetOf", () => {
    let a = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    let b = PersistentHashSet.fromArray([
      1,
      2
    ]);
    expect(PersistentHashSet.isSupersetOf(a, b)).toBe(true);
    expect(PersistentHashSet.isSupersetOf(b, a)).toBe(false);
  });
  test("filter keeps only matching elements", () => {
    let s = PersistentHashSet.fromArray([
      1,
      2,
      3,
      4,
      5
    ]);
    let even = PersistentHashSet.filter(s, x => x % 2 === 0);
    expect(PersistentHashSet.size(even)).toBe(2);
    expect(PersistentHashSet.has(even, 2)).toBe(true);
    expect(PersistentHashSet.has(even, 1)).toBe(false);
  });
  test("map transforms elements", () => {
    let s = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    let doubled = PersistentHashSet.map(s, x => (x << 1));
    expect(PersistentHashSet.has(doubled, 2)).toBe(true);
    expect(PersistentHashSet.has(doubled, 4)).toBe(true);
    expect(PersistentHashSet.has(doubled, 6)).toBe(true);
    expect(PersistentHashSet.size(doubled)).toBe(3);
  });
  test("empty set edge cases", () => {
    let empty = PersistentHashSet.make();
    let nonEmpty = PersistentHashSet.fromArray([
      1,
      2,
      3
    ]);
    expect(PersistentHashSet.equals(empty, empty)).toBe(true);
    expect(PersistentHashSet.isSubsetOf(empty, nonEmpty)).toBe(true);
    expect(PersistentHashSet.isSubsetOf(empty, empty)).toBe(true);
    expect(PersistentHashSet.isSupersetOf(nonEmpty, empty)).toBe(true);
    expect(PersistentHashSet.size(PersistentHashSet.filter(empty, param => true))).toBe(0);
    expect(PersistentHashSet.size(PersistentHashSet.map(empty, x => x))).toBe(0);
  });
});

let S;

export {
  S,
}
/*  Not a pure module */
