// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PersistentHashSet from "../src/PersistentHashSet.res.mjs";

describe("PersistentHashSet — basics", () => {
  test("empty set", () => {
    expect(PersistentHashSet.size(PersistentHashSet.make())).toBe(0);
    expect(PersistentHashSet.has(PersistentHashSet.make(), "x")).toBe(false);
  });
  test("add / has / remove", () => {
    let s = PersistentHashSet.add(PersistentHashSet.add(PersistentHashSet.add(PersistentHashSet.make(), "a"), "b"), "a");
    expect(PersistentHashSet.size(s)).toBe(2);
    expect(PersistentHashSet.has(s, "a")).toBe(true);
    expect(PersistentHashSet.has(s, "c")).toBe(false);
    let s2 = PersistentHashSet.remove(s, "a");
    expect(PersistentHashSet.size(s2)).toBe(1);
    expect(PersistentHashSet.has(s2, "a")).toBe(false);
    expect(PersistentHashSet.has(s, "a")).toBe(true);
  });
  test("set operations", () => {
    let a = PersistentHashSet.fromArray([
      "a",
      "b",
      "c",
      "d"
    ]);
    let b = PersistentHashSet.fromArray([
      "c",
      "d",
      "e",
      "f"
    ]);
    expect(PersistentHashSet.size(PersistentHashSet.union(a, b))).toBe(6);
    let inter = PersistentHashSet.intersect(a, b);
    expect(PersistentHashSet.size(inter)).toBe(2);
    expect(PersistentHashSet.has(inter, "c")).toBe(true);
    expect(PersistentHashSet.has(inter, "d")).toBe(true);
    let diff = PersistentHashSet.difference(a, b);
    expect(PersistentHashSet.size(diff)).toBe(2);
    expect(PersistentHashSet.has(diff, "a")).toBe(true);
    expect(PersistentHashSet.has(diff, "c")).toBe(false);
  });
  test("transient batch insert", () => {
    let s = PersistentHashSet.withTransient(PersistentHashSet.make(), t => {
      let cur = t;
      for (let i = 0; i <= 1999; ++i) {
        cur = PersistentHashSet.addMut(cur, "x" + i.toString());
      }
      return cur;
    });
    expect(PersistentHashSet.size(s)).toBe(2000);
    expect(PersistentHashSet.has(s, "x0")).toBe(true);
    expect(PersistentHashSet.has(s, "x1999")).toBe(true);
    expect(PersistentHashSet.has(s, "x2000")).toBe(false);
  });
  test("iterator visits each element once", () => {
    let s = PersistentHashSet.fromArray([
      "a",
      "b",
      "c",
      "d",
      "e"
    ]);
    let it = PersistentHashSet.iterator(s);
    let count = 0;
    let keep = true;
    while (keep) {
      let step = it.next();
      if (step.done) {
        keep = false;
      } else {
        count = count + 1 | 0;
      }
    };
    expect(count).toBe(5);
  });
});

let S;

export {
  S,
}
/*  Not a pure module */
