// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as PersistentVector from "../src/PersistentVector.res.mjs";
import * as PersistentHashMap from "../src/PersistentHashMap.res.mjs";

describe("Stack-overflow stress", () => {
  test("PersistentVector: push 1M elements via persistent path (exercises pushTail/newPath)", () => {
    let v = PersistentVector.make();
    for (let i = 0; i <= 999999; ++i) {
      v = PersistentVector.push(v, i);
    }
    expect(PersistentVector.size(v)).toBe(1000000);
    expect(PersistentVector.getExn(v, 0)).toBe(0);
    expect(PersistentVector.getExn(v, 999999)).toBe(999999);
    expect(PersistentVector.getExn(v, 500000)).toBe(500000);
  });
  test("PersistentVector: push 1M elements via transient (exercises tPushTail/pathFor)", () => {
    let built = PersistentVector.withTransient(PersistentVector.make(), t => {
      let cur = t;
      for (let i = 0; i <= 999999; ++i) {
        cur = PersistentVector.pushMut(cur, i);
      }
      return cur;
    });
    expect(PersistentVector.size(built)).toBe(1000000);
    expect(PersistentVector.getExn(built, 999999)).toBe(999999);
  });
  test("PersistentVector: 1M sets via persistent doSet then 1M pops via popTail", () => {
    let v = PersistentVector.fromArray(Core__Array.fromInitializer(1000000, param => 0));
    for (let i = 0; i <= 999999; ++i) {
      v = PersistentVector.set(v, i, i);
    }
    expect(PersistentVector.getExn(v, 333333)).toBe(333333);
    for (let _for = 1; _for <= 1000000; ++_for) {
      v = PersistentVector.pop(v);
    }
    expect(PersistentVector.size(v)).toBe(0);
  });
  test("PersistentHashMap: insert 1M keys via persistent path (exercises nodeAssoc/mergeKVs)", () => {
    let m = PersistentHashMap.make();
    for (let i = 0; i <= 999999; ++i) {
      m = PersistentHashMap.set(m, i, i);
    }
    expect(PersistentHashMap.size(m)).toBe(1000000);
    expect(PersistentHashMap.getExn(m, 0)).toBe(0);
    expect(PersistentHashMap.getExn(m, 999999)).toBe(999999);
  });
  test("PersistentHashMap: insert 1M keys via transient (exercises nodeAssocMut)", () => {
    let m = PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
      let cur = t;
      for (let i = 0; i <= 999999; ++i) {
        cur = PersistentHashMap.setMut(cur, i, i);
      }
      return cur;
    });
    expect(PersistentHashMap.size(m)).toBe(1000000);
    [
      0,
      1,
      500000,
      999999
    ].forEach(i => {
      expect(PersistentHashMap.getExn(m, i)).toBe(i);
    });
  });
  test("PersistentHashMap: 1M lookups (exercises nodeFind) and 1M removes (exercises nodeWithout)", () => {
    let m = PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
      let cur = t;
      for (let i = 0; i <= 999999; ++i) {
        cur = PersistentHashMap.setMut(cur, i, i);
      }
      return cur;
    });
    let sum = 0;
    for (let i = 0; i <= 999999; ++i) {
      sum = sum + PersistentHashMap.getExn(m, i) | 0;
    }
    expect(sum !== 0).toBe(true);
    for (let i$1 = 0; i$1 <= 999999; ++i$1) {
      m = PersistentHashMap.remove(m, i$1);
    }
    expect(PersistentHashMap.size(m)).toBe(0);
  });
});

let V;

let M;

let stressN = 1000000;

export {
  V,
  M,
  stressN,
}
/*  Not a pure module */
