// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function mix32(h) {
  let h$1 = h ^ (h >>> 16);
  let h$2 = Math.imul(h$1, -2048144789);
  let h$3 = h$2 ^ (h$2 >>> 13);
  let h$4 = Math.imul(h$3, -1028477387);
  let h$5 = h$4 ^ (h$4 >>> 16);
  return h$5 | 0;
}

function hashInt(n) {
  return mix32(n | 0);
}

function hashBool(b) {
  if (b) {
    return 1231;
  } else {
    return 1237;
  }
}

function hashString(s) {
  let h = 0;
  let len = s.length;
  for (let i = 0; i < len; ++i) {
    let c = s.charCodeAt(i) | 0;
    h = Math.imul(h, 31) + c | 0;
  }
  return mix32(h);
}

let _floatBuf = new ArrayBuffer(8);

let _floatF64 = new Float64Array(_floatBuf);

let _floatI32 = new Int32Array(_floatBuf);

function hashFloat(f) {
  _floatF64[0] = f;
  let lo = Core__Option.getOr(_floatI32[0], 0);
  let hi = Core__Option.getOr(_floatI32[1], 0);
  return mix32(lo ^ hi);
}

let _identityMap = new WeakMap();

let _identityCounter = {
  contents: 0
};

function identityHash(v) {
  let h = _identityMap.get(v);
  if (!(h == null)) {
    return h;
  }
  _identityCounter.contents = _identityCounter.contents + 1 | 0;
  let h$1 = mix32(_identityCounter.contents);
  _identityMap.set(v, h$1);
  return h$1;
}

function hash(v) {
  let t = typeof v;
  if (t === "bigint") {
    return hashString(String(v));
  }
  if (t === "boolean") {
    if (v) {
      return 1231;
    } else {
      return 1237;
    }
  }
  if (t === "string") {
    return hashString(v);
  }
  if (t === "object") {
    if (v === null) {
      return 0;
    } else {
      return identityHash(v);
    }
  }
  if (t === "undefined") {
    return 0;
  }
  if (t !== "number") {
    return identityHash(v);
  }
  let asInt = v | 0;
  if (asInt === v) {
    return mix32(asInt | 0);
  } else {
    return hashFloat(v);
  }
}

function equals(a, b) {
  return a === b;
}

function mask(hash, shift) {
  return (hash >>> shift) & 31;
}

function popcount(x) {
  let x$1 = x | 0;
  let x$2 = x$1 - ((x$1 >>> 1) & 1431655765) | 0;
  let x$3 = (x$2 & 858993459) + ((x$2 >>> 2) & 858993459) | 0;
  let x$4 = x$3 + (x$3 >>> 4) & 252645135;
  return (Math.imul(x$4, 16843009) >>> 24) & 63;
}

function bitpos(hash, shift) {
  return (1 << mask(hash, shift));
}

function arrayIndex(bitmap, bit) {
  return popcount(bitmap & (bit - 1 | 0));
}

export {
  mix32,
  hashInt,
  hashBool,
  hashString,
  hashFloat,
  identityHash,
  hash,
  equals,
  mask,
  popcount,
  bitpos,
  arrayIndex,
}
/* _floatBuf Not a pure module */
