// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";

function mix32(h) {
  let h$1 = h ^ (h >>> 16);
  let h$2 = Math.imul(h$1, -2048144789);
  let h$3 = h$2 ^ (h$2 >>> 13);
  let h$4 = Math.imul(h$3, -1028477387);
  let h$5 = h$4 ^ (h$4 >>> 16);
  return h$5 | 0;
}

function hashInt(n) {
  return mix32(n | 0);
}

function hashBool(b) {
  if (b) {
    return 1231;
  } else {
    return 1237;
  }
}

function hashString(s) {
  let h = 0;
  let len = s.length;
  for (let i = 0; i < len; ++i) {
    let c = s.charCodeAt(i) | 0;
    h = Math.imul(h, 31) + c | 0;
  }
  return mix32(h);
}

function hashFloat(f) {
  let buf = new ArrayBuffer(8);
  let f64 = new Float64Array(buf);
  let i32v = new Int32Array(buf);
  f64[0] = f;
  let lo = Core__Option.getOr(i32v[0], 0);
  let hi = Core__Option.getOr(i32v[1], 0);
  return mix32(lo ^ hi);
}

function hash(v) {
  let t = typeof v;
  if (t === "boolean") {
    if (v) {
      return 1231;
    } else {
      return 1237;
    }
  }
  if (t === "string") {
    return hashString(v);
  }
  if (t === "object") {
    if (v === null) {
      return 0;
    } else {
      return hashString(Core__Option.getOr(JSON.stringify(v), ""));
    }
  }
  if (t === "undefined") {
    return 0;
  }
  if (t !== "number") {
    return hashString(Core__Option.getOr(JSON.stringify(v), ""));
  }
  let asInt = v | 0;
  if (asInt === v) {
    return mix32(asInt | 0);
  } else {
    return hashFloat(v);
  }
}

function equals(a, b) {
  if (a === b) {
    return true;
  }
  let ta = typeof a;
  let tb = typeof b;
  if (ta !== tb || ta !== "object" || a === null || b === null) {
    return false;
  } else {
    return Primitive_object.equal(JSON.stringify(a), JSON.stringify(b));
  }
}

function mask(hash, shift) {
  return (hash >>> shift) & 31;
}

function popcount(x) {
  let x$1 = x | 0;
  let x$2 = x$1 - ((x$1 >>> 1) & 1431655765) | 0;
  let x$3 = (x$2 & 858993459) + ((x$2 >>> 2) & 858993459) | 0;
  let x$4 = x$3 + (x$3 >>> 4) & 252645135;
  return (Math.imul(x$4, 16843009) >>> 24) & 63;
}

function bitpos(hash, shift) {
  return (1 << mask(hash, shift));
}

function arrayIndex(bitmap, bit) {
  return popcount(bitmap & (bit - 1 | 0));
}

let B;

export {
  B,
  mix32,
  hashInt,
  hashBool,
  hashString,
  hashFloat,
  hash,
  equals,
  mask,
  popcount,
  bitpos,
  arrayIndex,
}
/* No side effect */
