// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hash from "./Hash.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let noEdit = {
  owned: false
};

function make() {
  return {
    size: 0,
    root: {
      TAG: "BitmapIndexed",
      edit: noEdit,
      bitmap: 0,
      array: []
    },
    nullEntry: undefined,
    undefinedEntry: undefined
  };
}

function size(m) {
  return m.size;
}

function isEmpty(m) {
  return m.size === 0;
}

function nodeFind(_n, _shift, hash, key) {
  while (true) {
    let shift = _shift;
    let n = _n;
    if (n.TAG === "BitmapIndexed") {
      let bitmap = n.bitmap;
      let array = n.array;
      let bit = Hash.bitpos(hash, shift);
      if ((bitmap & bit) === 0) {
        return;
      }
      let idx = Hash.arrayIndex(bitmap, bit);
      let child = array[idx];
      if (child.TAG === "KV") {
        if (Hash.equals(child._0, key)) {
          return Primitive_option.some(child._1);
        } else {
          return;
        }
      }
      _shift = shift + 5 | 0;
      _n = child._0;
      continue;
    }
    let nodeHash = n.hash;
    let array$1 = n.array;
    if (hash !== nodeHash) {
      return;
    }
    let len = array$1.length;
    let i = 0;
    let result;
    while (result === undefined && i < len) {
      let match = array$1[i];
      if (match.TAG === "KV" && Hash.equals(match._0, key)) {
        result = Primitive_option.some(match._1);
      }
      i = i + 1 | 0;
    };
    return result;
  };
}

function get(m, key) {
  if (key === null) {
    return Core__Option.map(m.nullEntry, param => param[1]);
  } else if (typeof key === "undefined") {
    return Core__Option.map(m.undefinedEntry, param => param[1]);
  } else {
    return nodeFind(m.root, 0, Hash.hash(key), key);
  }
}

function getExn(m, key) {
  let v = get(m, key);
  if (v !== undefined) {
    return Primitive_option.valFromOption(v);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function has(m, key) {
  if (key === null) {
    return Core__Option.isSome(m.nullEntry);
  } else if (typeof key === "undefined") {
    return Core__Option.isSome(m.undefinedEntry);
  } else {
    return nodeFind(m.root, 0, Hash.hash(key), key) !== undefined;
  }
}

function arrayInsert(array, idx, e) {
  let len = array.length;
  let out = Core__Array.make(len + 1 | 0, e);
  for (let i = 0; i < idx; ++i) {
    out[i] = array[i];
  }
  for (let i$1 = idx; i$1 < len; ++i$1) {
    out[i$1 + 1 | 0] = array[i$1];
  }
  return out;
}

function arrayRemoveAt(array, idx) {
  let len = array.length;
  let out = Core__Array.make(len - 1 | 0, array[0]);
  for (let i = 0; i < idx; ++i) {
    out[i] = array[i];
  }
  for (let i$1 = idx + 1 | 0; i$1 < len; ++i$1) {
    out[i$1 - 1 | 0] = array[i$1];
  }
  return out;
}

function arrayReplace(array, idx, e) {
  let out = array.slice();
  out[idx] = e;
  return out;
}

function mergeKVs(shift, h1, k1, v1, h2, k2, v2) {
  if (h1 === h2) {
    return {
      TAG: "HashCollision",
      edit: noEdit,
      hash: h1,
      array: [
        {
          TAG: "KV",
          _0: k1,
          _1: v1
        },
        {
          TAG: "KV",
          _0: k2,
          _1: v2
        }
      ]
    };
  }
  let bit1 = Hash.bitpos(h1, shift);
  let bit2 = Hash.bitpos(h2, shift);
  if (bit1 === bit2) {
    let child = mergeKVs(shift + 5 | 0, h1, k1, v1, h2, k2, v2);
    return {
      TAG: "BitmapIndexed",
      edit: noEdit,
      bitmap: bit1,
      array: [{
          TAG: "Sub",
          _0: child
        }]
    };
  }
  let bitmap = bit1 | bit2;
  let arr = Hash.arrayIndex(bitmap, bit1) === 0 ? [
      {
        TAG: "KV",
        _0: k1,
        _1: v1
      },
      {
        TAG: "KV",
        _0: k2,
        _1: v2
      }
    ] : [
      {
        TAG: "KV",
        _0: k2,
        _1: v2
      },
      {
        TAG: "KV",
        _0: k1,
        _1: v1
      }
    ];
  return {
    TAG: "BitmapIndexed",
    edit: noEdit,
    bitmap: bitmap,
    array: arr
  };
}

function nodeAssoc(_n, shift, hash, key, value, addedLeaf) {
  while (true) {
    let n = _n;
    if (n.TAG === "BitmapIndexed") {
      let bitmap = n.bitmap;
      let array = n.array;
      let bit = Hash.bitpos(hash, shift);
      let idx = Hash.arrayIndex(bitmap, bit);
      if ((bitmap & bit) === 0) {
        addedLeaf.contents = true;
        let newArr = arrayInsert(array, idx, {
          TAG: "KV",
          _0: key,
          _1: value
        });
        return {
          TAG: "BitmapIndexed",
          edit: noEdit,
          bitmap: bitmap | bit,
          array: newArr
        };
      }
      let child = array[idx];
      if (child.TAG === "KV") {
        let v = child._1;
        let k = child._0;
        if (Hash.equals(k, key)) {
          if (Hash.equals(v, value)) {
            return n;
          } else {
            return {
              TAG: "BitmapIndexed",
              edit: noEdit,
              bitmap: bitmap,
              array: arrayReplace(array, idx, {
                TAG: "KV",
                _0: key,
                _1: value
              })
            };
          }
        }
        addedLeaf.contents = true;
        let sub = mergeKVs(shift + 5 | 0, Hash.hash(k), k, v, hash, key, value);
        return {
          TAG: "BitmapIndexed",
          edit: noEdit,
          bitmap: bitmap,
          array: arrayReplace(array, idx, {
            TAG: "Sub",
            _0: sub
          })
        };
      }
      let child$1 = child._0;
      let newChild = nodeAssoc(child$1, shift + 5 | 0, hash, key, value, addedLeaf);
      if (newChild === child$1) {
        return n;
      } else {
        return {
          TAG: "BitmapIndexed",
          edit: noEdit,
          bitmap: bitmap,
          array: arrayReplace(array, idx, {
            TAG: "Sub",
            _0: newChild
          })
        };
      }
    }
    let nodeHash = n.hash;
    let array$1 = n.array;
    if (hash === nodeHash) {
      let len = array$1.length;
      let foundIdx = -1;
      for (let i = 0; i < len; ++i) {
        if (foundIdx < 0) {
          let match = array$1[i];
          if (match.TAG === "KV" && Hash.equals(match._0, key)) {
            foundIdx = i;
          }
        }
      }
      if (foundIdx >= 0) {
        return {
          TAG: "HashCollision",
          edit: noEdit,
          hash: nodeHash,
          array: arrayReplace(array$1, foundIdx, {
            TAG: "KV",
            _0: key,
            _1: value
          })
        };
      } else {
        addedLeaf.contents = true;
        return {
          TAG: "HashCollision",
          edit: noEdit,
          hash: nodeHash,
          array: arrayInsert(array$1, len, {
            TAG: "KV",
            _0: key,
            _1: value
          })
        };
      }
    }
    let wrapped = {
      TAG: "BitmapIndexed",
      edit: noEdit,
      bitmap: Hash.bitpos(nodeHash, shift),
      array: [{
          TAG: "Sub",
          _0: n
        }]
    };
    _n = wrapped;
    continue;
  };
}

function set(m, key, value) {
  if (key === null) {
    let added = Core__Option.isNone(m.nullEntry) ? 1 : 0;
    return {
      size: m.size + added | 0,
      root: m.root,
      nullEntry: [
        key,
        value
      ],
      undefinedEntry: m.undefinedEntry
    };
  }
  if (typeof key === "undefined") {
    let added$1 = Core__Option.isNone(m.undefinedEntry) ? 1 : 0;
    return {
      size: m.size + added$1 | 0,
      root: m.root,
      nullEntry: m.nullEntry,
      undefinedEntry: [
        key,
        value
      ]
    };
  }
  let added$2 = {
    contents: false
  };
  let newRoot = nodeAssoc(m.root, 0, Hash.hash(key), key, value, added$2);
  if (newRoot === m.root && !added$2.contents) {
    return m;
  } else {
    return {
      size: added$2.contents ? m.size + 1 | 0 : m.size,
      root: newRoot,
      nullEntry: m.nullEntry,
      undefinedEntry: m.undefinedEntry
    };
  }
}

function nodeWithout(n, shift, hash, key, removed) {
  if (n.TAG === "BitmapIndexed") {
    let bitmap = n.bitmap;
    let array = n.array;
    let bit = Hash.bitpos(hash, shift);
    if ((bitmap & bit) === 0) {
      return n;
    }
    let idx = Hash.arrayIndex(bitmap, bit);
    let child = array[idx];
    if (child.TAG === "KV") {
      if (Hash.equals(child._0, key)) {
        removed.contents = true;
        if (bitmap === bit) {
          return {
            TAG: "BitmapIndexed",
            edit: noEdit,
            bitmap: 0,
            array: []
          };
        } else {
          return {
            TAG: "BitmapIndexed",
            edit: noEdit,
            bitmap: bitmap ^ bit,
            array: arrayRemoveAt(array, idx)
          };
        }
      } else {
        return n;
      }
    }
    let child$1 = child._0;
    let newChild = nodeWithout(child$1, shift + 5 | 0, hash, key, removed);
    if (newChild === child$1) {
      return n;
    }
    let isEmpty;
    if (newChild.TAG === "BitmapIndexed") {
      let bitmap$1 = newChild.bitmap;
      isEmpty = bitmap$1 === 0;
    } else {
      isEmpty = false;
    }
    if (isEmpty) {
      if (bitmap === bit) {
        return {
          TAG: "BitmapIndexed",
          edit: noEdit,
          bitmap: 0,
          array: []
        };
      } else {
        return {
          TAG: "BitmapIndexed",
          edit: noEdit,
          bitmap: bitmap ^ bit,
          array: arrayRemoveAt(array, idx)
        };
      }
    } else {
      return {
        TAG: "BitmapIndexed",
        edit: noEdit,
        bitmap: bitmap,
        array: arrayReplace(array, idx, {
          TAG: "Sub",
          _0: newChild
        })
      };
    }
  }
  let nodeHash = n.hash;
  let array$1 = n.array;
  if (hash !== nodeHash) {
    return n;
  }
  let len = array$1.length;
  let foundIdx = -1;
  for (let i = 0; i < len; ++i) {
    if (foundIdx < 0) {
      let match = array$1[i];
      if (match.TAG === "KV" && Hash.equals(match._0, key)) {
        foundIdx = i;
      }
    }
  }
  if (foundIdx < 0) {
    return n;
  } else {
    removed.contents = true;
    if (len === 1) {
      return {
        TAG: "BitmapIndexed",
        edit: noEdit,
        bitmap: 0,
        array: []
      };
    } else {
      return {
        TAG: "HashCollision",
        edit: noEdit,
        hash: nodeHash,
        array: arrayRemoveAt(array$1, foundIdx)
      };
    }
  }
}

function remove(m, key) {
  if (key === null) {
    let removed = Core__Option.isSome(m.nullEntry) ? 1 : 0;
    return {
      size: m.size - removed | 0,
      root: m.root,
      nullEntry: undefined,
      undefinedEntry: m.undefinedEntry
    };
  }
  if (typeof key === "undefined") {
    let removed$1 = Core__Option.isSome(m.undefinedEntry) ? 1 : 0;
    return {
      size: m.size - removed$1 | 0,
      root: m.root,
      nullEntry: m.nullEntry,
      undefinedEntry: undefined
    };
  }
  let removed$2 = {
    contents: false
  };
  let newRoot = nodeWithout(m.root, 0, Hash.hash(key), key, removed$2);
  if (removed$2.contents) {
    return {
      size: m.size - 1 | 0,
      root: newRoot,
      nullEntry: m.nullEntry,
      undefinedEntry: m.undefinedEntry
    };
  } else {
    return m;
  }
}

function nodeForEach(n, f) {
  let array;
  if (n.TAG === "BitmapIndexed") {
    let array$1 = n.array;
    array = array$1;
  } else {
    let array$2 = n.array;
    array = array$2;
  }
  array.forEach(e => {
    if (e.TAG === "KV") {
      return f(e._0, e._1);
    } else {
      return nodeForEach(e._0, f);
    }
  });
}

function forEach(m, f) {
  let match = m.nullEntry;
  if (match !== undefined) {
    f(match[0], match[1]);
  }
  let match$1 = m.undefinedEntry;
  if (match$1 !== undefined) {
    f(match$1[0], match$1[1]);
  }
  nodeForEach(m.root, f);
}

function reduce(m, init, f) {
  let acc = {
    contents: init
  };
  forEach(m, (k, v) => {
    acc.contents = f(acc.contents, k, v);
  });
  return acc.contents;
}

function keys(m) {
  let out = [];
  forEach(m, (k, param) => {
    out.push(k);
  });
  return out;
}

function values(m) {
  let out = [];
  forEach(m, (param, v) => {
    out.push(v);
  });
  return out;
}

function entries(m) {
  let out = [];
  forEach(m, (k, v) => {
    out.push([
      k,
      v
    ]);
  });
  return out;
}

function fromEntries(entries) {
  let m = {
    contents: make()
  };
  entries.forEach(param => {
    m.contents = set(m.contents, param[0], param[1]);
  });
  return m.contents;
}

function iterator(m) {
  let nullDone = {
    contents: false
  };
  let undefDone = {
    contents: false
  };
  let stack = [];
  let stackIdxs = [];
  let match = m.root;
  let exit = 0;
  let array;
  if (match.TAG === "BitmapIndexed") {
    let array$1 = match.array;
    array = array$1;
    exit = 1;
  } else {
    let array$2 = match.array;
    array = array$2;
    exit = 1;
  }
  if (exit === 1) {
    if (array.length > 0) {
      stack.push(array);
      stackIdxs.push(0);
    }
  }
  let advance = () => {
    while (true) {
      if (nullDone.contents) {
        if (undefDone.contents) {
          let depth = stack.length;
          if (depth === 0) {
            return {
              value: undefined,
              done: true
            };
          }
          let arr = stack[depth - 1 | 0];
          let idx = stackIdxs[depth - 1 | 0];
          if (idx >= arr.length) {
            stack.pop();
            stackIdxs.pop();
            continue;
          }
          stackIdxs[depth - 1 | 0] = idx + 1 | 0;
          let child = arr[idx];
          if (child.TAG === "KV") {
            return {
              value: [
                child._0,
                child._1
              ],
              done: false
            };
          }
          let child$1 = child._0;
          let exit = 0;
          let array;
          if (child$1.TAG === "BitmapIndexed") {
            let array$1 = child$1.array;
            array = array$1;
            exit = 1;
          } else {
            let array$2 = child$1.array;
            array = array$2;
            exit = 1;
          }
          if (exit === 1) {
            stack.push(array);
            stackIdxs.push(0);
          }
          continue;
        }
        undefDone.contents = true;
        let pair = m.undefinedEntry;
        if (pair !== undefined) {
          return {
            value: pair,
            done: false
          };
        }
        continue;
      }
      nullDone.contents = true;
      let pair$1 = m.nullEntry;
      if (pair$1 !== undefined) {
        return {
          value: pair$1,
          done: false
        };
      }
      continue;
    };
  };
  return {
    next: advance
  };
}

function asTransient(m) {
  return {
    size: m.size,
    root: m.root,
    nullEntry: m.nullEntry,
    undefinedEntry: m.undefinedEntry,
    edit: {
      owned: true
    }
  };
}

function ensureEditable(t) {
  if (t.edit.owned) {
    return;
  }
  throw {
    RE_EXN_ID: "Invalid_argument",
    _1: "transient used after persistent! was called",
    Error: new Error()
  };
}

function nodeAssocMut(ownEdit, _n, shift, hash, key, value, addedLeaf) {
  while (true) {
    let n = _n;
    if (n.TAG === "BitmapIndexed") {
      let bit = Hash.bitpos(hash, shift);
      let idx = Hash.arrayIndex(n.bitmap, bit);
      if ((n.bitmap & bit) === 0) {
        addedLeaf.contents = true;
        let newArr = arrayInsert(n.array, idx, {
          TAG: "KV",
          _0: key,
          _1: value
        });
        if (n.edit === ownEdit) {
          n.bitmap = n.bitmap | bit;
          n.array = newArr;
          return n;
        } else {
          return {
            TAG: "BitmapIndexed",
            edit: ownEdit,
            bitmap: n.bitmap | bit,
            array: newArr
          };
        }
      }
      let child = n.array[idx];
      if (child.TAG === "KV") {
        let v = child._1;
        let k = child._0;
        if (Hash.equals(k, key)) {
          if (Hash.equals(v, value)) {
            return n;
          }
          let newArr$1 = n.edit === ownEdit ? (n.array[idx] = {
              TAG: "KV",
              _0: key,
              _1: value
            }, n.array) : arrayReplace(n.array, idx, {
              TAG: "KV",
              _0: key,
              _1: value
            });
          if (n.edit === ownEdit) {
            return n;
          } else {
            return {
              TAG: "BitmapIndexed",
              edit: ownEdit,
              bitmap: n.bitmap,
              array: newArr$1
            };
          }
        }
        addedLeaf.contents = true;
        let sub = mergeKVs(shift + 5 | 0, Hash.hash(k), k, v, hash, key, value);
        let newArr$2 = n.edit === ownEdit ? (n.array[idx] = {
            TAG: "Sub",
            _0: sub
          }, n.array) : arrayReplace(n.array, idx, {
            TAG: "Sub",
            _0: sub
          });
        if (n.edit === ownEdit) {
          return n;
        } else {
          return {
            TAG: "BitmapIndexed",
            edit: ownEdit,
            bitmap: n.bitmap,
            array: newArr$2
          };
        }
      }
      let child$1 = child._0;
      let newChild = nodeAssocMut(ownEdit, child$1, shift + 5 | 0, hash, key, value, addedLeaf);
      if (newChild === child$1) {
        return n;
      }
      let newArr$3 = n.edit === ownEdit ? (n.array[idx] = {
          TAG: "Sub",
          _0: newChild
        }, n.array) : arrayReplace(n.array, idx, {
          TAG: "Sub",
          _0: newChild
        });
      if (n.edit === ownEdit) {
        return n;
      } else {
        return {
          TAG: "BitmapIndexed",
          edit: ownEdit,
          bitmap: n.bitmap,
          array: newArr$3
        };
      }
    }
    if (hash === n.hash) {
      let len = n.array.length;
      let foundIdx = -1;
      for (let i = 0; i < len; ++i) {
        if (foundIdx < 0) {
          let match = n.array[i];
          if (match.TAG === "KV" && Hash.equals(match._0, key)) {
            foundIdx = i;
          }
        }
      }
      if (foundIdx >= 0) {
        let newArr$4 = n.edit === ownEdit ? (n.array[foundIdx] = {
            TAG: "KV",
            _0: key,
            _1: value
          }, n.array) : arrayReplace(n.array, foundIdx, {
            TAG: "KV",
            _0: key,
            _1: value
          });
        if (n.edit === ownEdit) {
          return n;
        } else {
          return {
            TAG: "HashCollision",
            edit: ownEdit,
            hash: n.hash,
            array: newArr$4
          };
        }
      }
      addedLeaf.contents = true;
      let newArr$5 = arrayInsert(n.array, len, {
        TAG: "KV",
        _0: key,
        _1: value
      });
      if (n.edit === ownEdit) {
        n.array = newArr$5;
        return n;
      } else {
        return {
          TAG: "HashCollision",
          edit: ownEdit,
          hash: n.hash,
          array: newArr$5
        };
      }
    }
    let wrapped = {
      TAG: "BitmapIndexed",
      edit: ownEdit,
      bitmap: Hash.bitpos(n.hash, shift),
      array: [{
          TAG: "Sub",
          _0: n
        }]
    };
    _n = wrapped;
    continue;
  };
}

function setMut(t, key, value) {
  ensureEditable(t);
  if (key === null) {
    if (Core__Option.isNone(t.nullEntry)) {
      t.size = t.size + 1 | 0;
    }
    t.nullEntry = [
      key,
      value
    ];
    return t;
  }
  if (typeof key === "undefined") {
    if (Core__Option.isNone(t.undefinedEntry)) {
      t.size = t.size + 1 | 0;
    }
    t.undefinedEntry = [
      key,
      value
    ];
    return t;
  }
  let added = {
    contents: false
  };
  let newRoot = nodeAssocMut(t.edit, t.root, 0, Hash.hash(key), key, value, added);
  t.root = newRoot;
  if (added.contents) {
    t.size = t.size + 1 | 0;
  }
  return t;
}

function removeMut(t, key) {
  ensureEditable(t);
  if (key === null) {
    if (Core__Option.isSome(t.nullEntry)) {
      t.nullEntry = undefined;
      t.size = t.size - 1 | 0;
    }
    return t;
  }
  if (typeof key === "undefined") {
    if (Core__Option.isSome(t.undefinedEntry)) {
      t.undefinedEntry = undefined;
      t.size = t.size - 1 | 0;
    }
    return t;
  }
  let removed = {
    contents: false
  };
  let newRoot = nodeWithout(t.root, 0, Hash.hash(key), key, removed);
  t.root = newRoot;
  if (removed.contents) {
    t.size = t.size - 1 | 0;
  }
  return t;
}

function getMut(t, key) {
  ensureEditable(t);
  if (key === null) {
    return Core__Option.map(t.nullEntry, param => param[1]);
  } else if (typeof key === "undefined") {
    return Core__Option.map(t.undefinedEntry, param => param[1]);
  } else {
    return nodeFind(t.root, 0, Hash.hash(key), key);
  }
}

function persistent(t) {
  ensureEditable(t);
  t.edit.owned = false;
  return {
    size: t.size,
    root: t.root,
    nullEntry: t.nullEntry,
    undefinedEntry: t.undefinedEntry
  };
}

function withTransient(m, f) {
  return persistent(f(asTransient(m)));
}

function equals(a, b, eq) {
  if (a.size !== b.size) {
    return false;
  }
  let same = {
    contents: true
  };
  forEach(a, (k, v) => {
    let v2 = get(b, k);
    if (v2 !== undefined && eq(v, Primitive_option.valFromOption(v2))) {
      return;
    } else {
      same.contents = false;
      return;
    }
  });
  return same.contents;
}

function merge(a, b) {
  let t = asTransient(a);
  return persistent((forEach(b, (k, v) => {
    setMut(t, k, v);
  }), t));
}

function map(m, f) {
  let m$1 = make();
  let t = asTransient(m$1);
  return persistent((forEach(m, (k, v) => {
    setMut(t, k, f(v));
  }), t));
}

function filter(m, f) {
  let m$1 = make();
  let t = asTransient(m$1);
  return persistent((forEach(m, (k, v) => {
    if (f(k, v)) {
      setMut(t, k, v);
      return;
    }
  }), t));
}

function update(m, key, f) {
  let current = get(m, key);
  let v = f(current);
  if (v !== undefined) {
    return set(m, key, Primitive_option.valFromOption(v));
  } else if (current !== undefined) {
    return remove(m, key);
  } else {
    return m;
  }
}

export {
  make,
  size,
  isEmpty,
  get,
  getExn,
  has,
  set,
  remove,
  forEach,
  reduce,
  keys,
  values,
  entries,
  fromEntries,
  iterator,
  equals,
  merge,
  map,
  filter,
  update,
  asTransient,
  setMut,
  removeMut,
  getMut,
  persistent,
  withTransient,
}
/* Hash Not a pure module */
