// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let noEdit = {
  owned: false
};

function make() {
  return {
    size: 0,
    shift: 5,
    root: {
      edit: noEdit,
      array: Core__Array.make(32, "Empty")
    },
    tail: []
  };
}

function size(v) {
  return v.size;
}

function tailOffset(v) {
  if (v.size < 32) {
    return 0;
  } else {
    return (((v.size - 1 | 0) >>> 5) << 5);
  }
}

function arrayFor(v, i) {
  if (i < 0 || i >= v.size) {
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  }
  if (i >= tailOffset(v)) {
    return v.tail;
  }
  let node = v.root;
  let level = v.shift;
  while (level > 0) {
    let idx = (i >>> level) & 31;
    let n = node.array[idx];
    if (typeof n !== "object") {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
    if (n.TAG === "Branch") {
      node = n._0;
    } else {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
    level = level - 5 | 0;
  };
  let result = Core__Array.make(32, 0);
  node.array.forEach((slot, j) => {
    if (typeof slot !== "object" || slot.TAG === "Branch") {
      return;
    } else {
      result[j] = slot._0;
      return;
    }
  });
  return result;
}

function get(v, i) {
  if (i < 0 || i >= v.size) {
    return;
  }
  if (i >= tailOffset(v)) {
    return v.tail[i - tailOffset(v) | 0];
  }
  let node = v.root;
  let level = v.shift;
  while (level > 0) {
    let idx = (i >>> level) & 31;
    let n = node.array[idx];
    if (typeof n !== "object" || n.TAG !== "Branch") {
      level = -1;
    } else {
      node = n._0;
    }
    if (level >= 0) {
      level = level - 5 | 0;
    }
  };
  let x = node.array[i & 31];
  if (typeof x !== "object" || x.TAG === "Branch") {
    return;
  } else {
    return Primitive_option.some(x._0);
  }
}

function getExn(v, i) {
  let x = get(v, i);
  if (x !== undefined) {
    return Primitive_option.valFromOption(x);
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function cloneNode(n) {
  return {
    edit: n.edit,
    array: n.array.slice()
  };
}

function newPath(level, tail) {
  if (level === 0) {
    let arr = Core__Array.make(32, "Empty");
    tail.forEach((x, i) => {
      arr[i] = {
        TAG: "Leaf",
        _0: x
      };
    });
    return {
      edit: noEdit,
      array: arr
    };
  }
  let n_array = Core__Array.make(32, "Empty");
  let n = {
    edit: noEdit,
    array: n_array
  };
  n_array[0] = {
    TAG: "Branch",
    _0: newPath(level - 5 | 0, tail)
  };
  return n;
}

function pushTail(level, parent, tail, size) {
  let subIdx = ((size - 1 | 0) >>> level) & 31;
  let result = cloneNode(parent);
  let nodeToInsert;
  if (level === 5) {
    let leafNode_array = Core__Array.make(32, "Empty");
    let leafNode = {
      edit: noEdit,
      array: leafNode_array
    };
    tail.forEach((x, i) => {
      leafNode_array[i] = {
        TAG: "Leaf",
        _0: x
      };
    });
    nodeToInsert = leafNode;
  } else {
    let child = parent.array[subIdx];
    nodeToInsert = typeof child !== "object" || child.TAG !== "Branch" ? newPath(level - 5 | 0, tail) : pushTail(level - 5 | 0, child._0, tail, size);
  }
  result.array[subIdx] = {
    TAG: "Branch",
    _0: nodeToInsert
  };
  return result;
}

function push(v, x) {
  if ((v.size - tailOffset(v) | 0) < 32) {
    let newTail = v.tail.slice();
    newTail.push(x);
    return {
      size: v.size + 1 | 0,
      shift: v.shift,
      root: v.root,
      tail: newTail
    };
  }
  let match;
  if ((v.size >>> 5) > (1 << v.shift)) {
    let nr_array = Core__Array.make(32, "Empty");
    let nr = {
      edit: noEdit,
      array: nr_array
    };
    nr_array[0] = {
      TAG: "Branch",
      _0: v.root
    };
    nr_array[1] = {
      TAG: "Branch",
      _0: newPath(v.shift, v.tail)
    };
    match = [
      nr,
      v.shift + 5 | 0
    ];
  } else {
    match = [
      pushTail(v.shift, v.root, v.tail, v.size),
      v.shift
    ];
  }
  return {
    size: v.size + 1 | 0,
    shift: match[1],
    root: match[0],
    tail: [x]
  };
}

function doSet(level, n, i, x) {
  let cloned = cloneNode(n);
  if (level === 0) {
    cloned.array[i & 31] = {
      TAG: "Leaf",
      _0: x
    };
  } else {
    let subIdx = (i >>> level) & 31;
    let child = n.array[subIdx];
    if (typeof child !== "object") {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
    if (child.TAG === "Branch") {
      cloned.array[subIdx] = {
        TAG: "Branch",
        _0: doSet(level - 5 | 0, child._0, i, x)
      };
    } else {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
  }
  return cloned;
}

function set(v, i, x) {
  if (i < 0 || i > v.size) {
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  }
  if (i === v.size) {
    return push(v, x);
  }
  if (i < tailOffset(v)) {
    return {
      size: v.size,
      shift: v.shift,
      root: doSet(v.shift, v.root, i, x),
      tail: v.tail
    };
  }
  let newTail = v.tail.slice();
  newTail[i - tailOffset(v) | 0] = x;
  return {
    size: v.size,
    shift: v.shift,
    root: v.root,
    tail: newTail
  };
}

function popTail(level, n, size) {
  let subIdx = ((size - 2 | 0) >>> level) & 31;
  if (level > 5) {
    let child = n.array[subIdx];
    if (typeof child !== "object") {
      return;
    }
    if (child.TAG !== "Branch") {
      return;
    }
    let newChild = popTail(level - 5 | 0, child._0, size);
    if (newChild !== undefined) {
      let cloned = cloneNode(n);
      cloned.array[subIdx] = {
        TAG: "Branch",
        _0: newChild
      };
      return cloned;
    }
    if (subIdx === 0) {
      return;
    }
    let cloned$1 = cloneNode(n);
    cloned$1.array[subIdx] = "Empty";
    return cloned$1;
  } else {
    if (subIdx === 0) {
      return;
    }
    let cloned$2 = cloneNode(n);
    cloned$2.array[subIdx] = "Empty";
    return cloned$2;
  }
}

function pop(v) {
  let match = v.size;
  if (match !== 0) {
    if (match === 1) {
      return make();
    }
    if ((v.size - tailOffset(v) | 0) > 1) {
      let newTail = v.tail.slice();
      newTail.pop();
      return {
        size: v.size - 1 | 0,
        shift: v.shift,
        root: v.root,
        tail: newTail
      };
    }
    let newTail$1 = arrayFor(v, v.size - 2 | 0);
    let newRootOpt = popTail(v.shift, v.root, v.size);
    let match$1;
    if (newRootOpt !== undefined) {
      if (v.shift > 5) {
        let match$2 = newRootOpt.array[1];
        if (typeof match$2 !== "object") {
          let child = newRootOpt.array[0];
          match$1 = typeof child !== "object" || child.TAG !== "Branch" ? [
              newRootOpt,
              v.shift
            ] : [
              child._0,
              v.shift - 5 | 0
            ];
        } else {
          match$1 = [
            newRootOpt,
            v.shift
          ];
        }
      } else {
        match$1 = [
          newRootOpt,
          v.shift
        ];
      }
    } else {
      match$1 = [
        {
          edit: noEdit,
          array: Core__Array.make(32, "Empty")
        },
        5
      ];
    }
    return {
      size: v.size - 1 | 0,
      shift: match$1[1],
      root: match$1[0],
      tail: newTail$1
    };
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function fromArray(arr) {
  let v = {
    contents: make()
  };
  arr.forEach(x => {
    v.contents = push(v.contents, x);
  });
  return v.contents;
}

function toArray(v) {
  let out = Core__Array.make(v.size, 0);
  let i = 0;
  while (i < v.size) {
    let leaf = arrayFor(v, i);
    let baseIdx = i - (i & 31) | 0;
    let copyLen = Math.min(32, v.size - baseIdx | 0);
    for (let j = 0; j < copyLen; ++j) {
      out[baseIdx + j | 0] = leaf[j];
    }
    i = baseIdx + copyLen | 0;
  };
  return out;
}

function forEach(v, f) {
  let i = 0;
  while (i < v.size) {
    let leaf = arrayFor(v, i);
    let baseIdx = i - (i & 31) | 0;
    let copyLen = Math.min(32, v.size - baseIdx | 0);
    for (let j = 0; j < copyLen; ++j) {
      f(leaf[j]);
    }
    i = baseIdx + copyLen | 0;
  };
}

function forEachWithIndex(v, f) {
  let i = 0;
  while (i < v.size) {
    let leaf = arrayFor(v, i);
    let baseIdx = i - (i & 31) | 0;
    let copyLen = Math.min(32, v.size - baseIdx | 0);
    for (let j = 0; j < copyLen; ++j) {
      f(leaf[j], baseIdx + j | 0);
    }
    i = baseIdx + copyLen | 0;
  };
}

function reduce(v, init, f) {
  let acc = {
    contents: init
  };
  forEach(v, x => {
    acc.contents = f(acc.contents, x);
  });
  return acc.contents;
}

function map(v, f) {
  let out = {
    contents: make()
  };
  forEach(v, x => {
    out.contents = push(out.contents, f(x));
  });
  return out.contents;
}

function filter(v, f) {
  let out = {
    contents: make()
  };
  forEach(v, x => {
    if (f(x)) {
      out.contents = push(out.contents, x);
      return;
    }
  });
  return out.contents;
}

function equals(a, b, eq) {
  if (a.size !== b.size) {
    return false;
  }
  let same = true;
  let i = 0;
  while (same && i < a.size) {
    let av = arrayFor(a, i);
    let bv = arrayFor(b, i);
    let baseIdx = i - (i & 31) | 0;
    let copyLen = Math.min(32, a.size - baseIdx | 0);
    for (let j = 0; j < copyLen; ++j) {
      if (!eq(av[j], bv[j])) {
        same = false;
      }
    }
    i = baseIdx + copyLen | 0;
  };
  return same;
}

function iterator(v) {
  let i = {
    contents: 0
  };
  let leafCache = {
    contents: v.size > 0 ? arrayFor(v, 0) : []
  };
  let leafBase = {
    contents: 0
  };
  let next = () => {
    if (i.contents >= v.size) {
      return {
        value: undefined,
        done: true
      };
    }
    if ((i.contents - leafBase.contents | 0) >= 32) {
      leafCache.contents = arrayFor(v, i.contents);
      leafBase.contents = i.contents - (i.contents & 31) | 0;
    }
    let v$1 = leafCache.contents[i.contents - leafBase.contents | 0];
    i.contents = i.contents + 1 | 0;
    return {
      value: Primitive_option.some(v$1),
      done: false
    };
  };
  return {
    next: next
  };
}

function asTransient(v) {
  let edit = {
    owned: true
  };
  let bigTail = Core__Array.make(32, 0);
  v.tail.forEach((x, i) => {
    bigTail[i] = x;
  });
  return {
    size: v.size,
    shift: v.shift,
    root: {
      edit: edit,
      array: v.root.array.slice()
    },
    tail: bigTail,
    edit: edit
  };
}

function ensureEditable(t) {
  if (t.edit.owned) {
    return;
  }
  throw {
    RE_EXN_ID: "Invalid_argument",
    _1: "transient used after persistent! was called",
    Error: new Error()
  };
}

function editableNode(edit, n) {
  if (n.edit === edit) {
    return n;
  } else {
    return {
      edit: edit,
      array: n.array.slice()
    };
  }
}

function pathFor(edit, level, tailNode) {
  if (level === 0) {
    return tailNode;
  }
  let n_array = Core__Array.make(32, "Empty");
  let n = {
    edit: edit,
    array: n_array
  };
  n_array[0] = {
    TAG: "Branch",
    _0: pathFor(edit, level - 5 | 0, tailNode)
  };
  return n;
}

function tPushTail(edit, level, parent, tailNode, size) {
  let subIdx = ((size - 1 | 0) >>> level) & 31;
  let parent$1 = editableNode(edit, parent);
  let nodeToInsert;
  if (level === 5) {
    nodeToInsert = tailNode;
  } else {
    let child = parent$1.array[subIdx];
    nodeToInsert = typeof child !== "object" || child.TAG !== "Branch" ? pathFor(edit, level - 5 | 0, tailNode) : tPushTail(edit, level - 5 | 0, child._0, tailNode, size);
  }
  parent$1.array[subIdx] = {
    TAG: "Branch",
    _0: nodeToInsert
  };
  return parent$1;
}

function pushMut(t, x) {
  ensureEditable(t);
  let snapshotForOff_size = t.size;
  let snapshotForOff_shift = t.shift;
  let snapshotForOff_root = t.root;
  let snapshotForOff_tail = [];
  let snapshotForOff = {
    size: snapshotForOff_size,
    shift: snapshotForOff_shift,
    root: snapshotForOff_root,
    tail: snapshotForOff_tail
  };
  let tailLen = t.size - tailOffset(snapshotForOff) | 0;
  if (tailLen < 32) {
    t.tail[tailLen] = x;
    t.size = t.size + 1 | 0;
    return t;
  }
  let a = Core__Array.make(32, "Empty");
  for (let i = 0; i <= 31; ++i) {
    a[i] = {
      TAG: "Leaf",
      _0: t.tail[i]
    };
  }
  let tailNode_edit = t.edit;
  let tailNode = {
    edit: tailNode_edit,
    array: a
  };
  let newTail = Core__Array.make(32, 0);
  newTail[0] = x;
  if ((t.size >>> 5) > (1 << t.shift)) {
    let newRoot_edit = t.edit;
    let newRoot_array = Core__Array.make(32, "Empty");
    let newRoot = {
      edit: newRoot_edit,
      array: newRoot_array
    };
    newRoot_array[0] = {
      TAG: "Branch",
      _0: t.root
    };
    newRoot_array[1] = {
      TAG: "Branch",
      _0: pathFor(t.edit, t.shift, tailNode)
    };
    t.root = newRoot;
    t.shift = t.shift + 5 | 0;
  } else {
    t.root = tPushTail(t.edit, t.shift, t.root, tailNode, t.size);
  }
  t.tail = newTail;
  t.size = t.size + 1 | 0;
  return t;
}

function setMut(t, i, x) {
  ensureEditable(t);
  if (i < 0 || i > t.size) {
    throw {
      RE_EXN_ID: "Not_found",
      Error: new Error()
    };
  }
  if (i === t.size) {
    return pushMut(t, x);
  }
  let snapshot_size = t.size;
  let snapshot_shift = t.shift;
  let snapshot_root = t.root;
  let snapshot_tail = t.tail;
  let snapshot = {
    size: snapshot_size,
    shift: snapshot_shift,
    root: snapshot_root,
    tail: snapshot_tail
  };
  let off = tailOffset(snapshot);
  if (i >= off) {
    t.tail[i - off | 0] = x;
    return t;
  }
  let level = t.shift;
  let n = editableNode(t.edit, t.root);
  t.root = n;
  while (level > 0) {
    let subIdx = (i >>> level) & 31;
    let child = n.array[subIdx];
    if (typeof child !== "object") {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
    if (child.TAG === "Branch") {
      let owned = editableNode(t.edit, child._0);
      n.array[subIdx] = {
        TAG: "Branch",
        _0: owned
      };
      n = owned;
    } else {
      throw {
        RE_EXN_ID: "Not_found",
        Error: new Error()
      };
    }
    level = level - 5 | 0;
  };
  n.array[i & 31] = {
    TAG: "Leaf",
    _0: x
  };
  return t;
}

function getMut(t, i) {
  ensureEditable(t);
  let snapshot_size = t.size;
  let snapshot_shift = t.shift;
  let snapshot_root = t.root;
  let snapshot_tail = t.tail;
  let snapshot = {
    size: snapshot_size,
    shift: snapshot_shift,
    root: snapshot_root,
    tail: snapshot_tail
  };
  if (i < 0 || i >= t.size) {
    return;
  } else if (i >= tailOffset(snapshot)) {
    return Primitive_option.some(t.tail[i - tailOffset(snapshot) | 0]);
  } else {
    return get(snapshot, i);
  }
}

function persistent(t) {
  ensureEditable(t);
  t.edit.owned = false;
  let off = tailOffset({
    size: t.size,
    shift: t.shift,
    root: t.root,
    tail: []
  });
  let tailLen = t.size - off | 0;
  let trimmedTail = Core__Array.make(tailLen, 0);
  for (let i = 0; i < tailLen; ++i) {
    trimmedTail[i] = t.tail[i];
  }
  return {
    size: t.size,
    shift: t.shift,
    root: t.root,
    tail: trimmedTail
  };
}

function withTransient(v, f) {
  return persistent(f(asTransient(v)));
}

let length = size;

export {
  make,
  size,
  length,
  get,
  getExn,
  push,
  set,
  pop,
  fromArray,
  toArray,
  forEach,
  forEachWithIndex,
  reduce,
  map,
  filter,
  equals,
  iterator,
  asTransient,
  pushMut,
  setMut,
  getMut,
  persistent,
  withTransient,
}
/* No side effect */
