// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as PersistentHashMap from "./PersistentHashMap.res.mjs";

function make() {
  return PersistentHashMap.make();
}

let size = PersistentHashMap.size;

let isEmpty = PersistentHashMap.isEmpty;

let has = PersistentHashMap.has;

function add(s, x) {
  return PersistentHashMap.set(s, x, undefined);
}

let remove = PersistentHashMap.remove;

function fromArray(arr) {
  let s = {
    contents: PersistentHashMap.make()
  };
  arr.forEach(x => {
    s.contents = PersistentHashMap.set(s.contents, x, undefined);
  });
  return s.contents;
}

let toArray = PersistentHashMap.keys;

function forEach(s, f) {
  PersistentHashMap.forEach(s, (k, param) => f(k));
}

function reduce(s, init, f) {
  return PersistentHashMap.reduce(s, init, (acc, k, param) => f(acc, k));
}

let union = PersistentHashMap.merge;

function intersect(a, b) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(a, (k, param) => {
      if (PersistentHashMap.has(b, k)) {
        PersistentHashMap.setMut(t, k, undefined);
        return;
      }
    });
    return t;
  });
}

function difference(a, b) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(a, (k, param) => {
      if (!PersistentHashMap.has(b, k)) {
        PersistentHashMap.setMut(t, k, undefined);
        return;
      }
    });
    return t;
  });
}

function iterator(s) {
  let inner = PersistentHashMap.iterator(s);
  let next = () => {
    let step = inner.next();
    if (step.done) {
      return {
        value: undefined,
        done: true
      };
    }
    let match = step.value;
    if (match !== undefined) {
      return {
        value: Primitive_option.some(match[0]),
        done: false
      };
    } else {
      return {
        value: undefined,
        done: true
      };
    }
  };
  return {
    next: next
  };
}

let asTransient = PersistentHashMap.asTransient;

function addMut(t, x) {
  return PersistentHashMap.setMut(t, x, undefined);
}

let removeMut = PersistentHashMap.removeMut;

function hasMut(t, x) {
  return PersistentHashMap.getMut(t, x) !== undefined;
}

let persistent = PersistentHashMap.persistent;

function withTransient(s, f) {
  return PersistentHashMap.persistent(f(PersistentHashMap.asTransient(s)));
}

function isSubsetOf(a, b) {
  if (PersistentHashMap.size(a) > PersistentHashMap.size(b)) {
    return false;
  }
  let isSubset = {
    contents: true
  };
  PersistentHashMap.forEach(a, (k, param) => {
    if (isSubset.contents && !PersistentHashMap.has(b, k)) {
      isSubset.contents = false;
      return;
    }
  });
  return isSubset.contents;
}

function equals(a, b) {
  if (PersistentHashMap.size(a) === PersistentHashMap.size(b)) {
    return isSubsetOf(a, b);
  } else {
    return false;
  }
}

function isSupersetOf(a, b) {
  return isSubsetOf(b, a);
}

function filter(s, f) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(s, (k, param) => {
      if (f(k)) {
        PersistentHashMap.setMut(t, k, undefined);
        return;
      }
    });
    return t;
  });
}

function map(s, f) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(s, (k, param) => {
      PersistentHashMap.setMut(t, f(k), undefined);
    });
    return t;
  });
}

export {
  make,
  size,
  isEmpty,
  has,
  add,
  remove,
  fromArray,
  toArray,
  forEach,
  reduce,
  union,
  intersect,
  difference,
  iterator,
  asTransient,
  addMut,
  removeMut,
  hasMut,
  persistent,
  withTransient,
  equals,
  isSubsetOf,
  isSupersetOf,
  filter,
  map,
}
/* PersistentHashMap Not a pure module */
