// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function make() {
  return {
    size: 0,
    front: /* [] */0,
    rear: /* [] */0
  };
}

function size(q) {
  return q.size;
}

function isEmpty(q) {
  return q.size === 0;
}

function balance(q) {
  let match = q.front;
  if (match !== 0) {
    return q;
  } else {
    return {
      size: q.size,
      front: Core__List.reverse(q.rear),
      rear: /* [] */0
    };
  }
}

function enqueue(q, x) {
  return balance({
    size: q.size + 1 | 0,
    front: q.front,
    rear: {
      hd: x,
      tl: q.rear
    }
  });
}

function peek(q) {
  let match = q.front;
  if (match !== 0) {
    return Primitive_option.some(match.hd);
  }
}

function peekExn(q) {
  let match = q.front;
  if (match !== 0) {
    return match.hd;
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function dequeue(q) {
  let match = q.front;
  if (match !== 0) {
    return [
      match.hd,
      balance({
        size: q.size - 1 | 0,
        front: match.tl,
        rear: q.rear
      })
    ];
  }
}

function dequeueExn(q) {
  let pair = dequeue(q);
  if (pair !== undefined) {
    return pair;
  }
  throw {
    RE_EXN_ID: "Not_found",
    Error: new Error()
  };
}

function toArray(q) {
  let out = Core__Array.make(q.size, 0);
  let i = 0;
  let cur = q;
  while (cur.size !== 0) {
    let match = dequeue(cur);
    if (match !== undefined) {
      out[i] = match[0];
      i = i + 1 | 0;
      cur = match[1];
    }
  };
  return out;
}

function fromArray(arr) {
  let q = {
    contents: {
      size: 0,
      front: /* [] */0,
      rear: /* [] */0
    }
  };
  arr.forEach(x => {
    q.contents = enqueue(q.contents, x);
  });
  return q.contents;
}

function forEach(q, f) {
  toArray(q).forEach(f);
}

function reduce(q, init, f) {
  let acc = {
    contents: init
  };
  forEach(q, x => {
    acc.contents = f(acc.contents, x);
  });
  return acc.contents;
}

function map(q, f) {
  let out = {
    contents: {
      size: 0,
      front: /* [] */0,
      rear: /* [] */0
    }
  };
  forEach(q, x => {
    out.contents = enqueue(out.contents, f(x));
  });
  return out.contents;
}

function filter(q, f) {
  let out = {
    contents: {
      size: 0,
      front: /* [] */0,
      rear: /* [] */0
    }
  };
  forEach(q, x => {
    if (f(x)) {
      out.contents = enqueue(out.contents, x);
      return;
    }
  });
  return out.contents;
}

function iterator(q) {
  let cur = {
    contents: q
  };
  let next = () => {
    let match = dequeue(cur.contents);
    if (match !== undefined) {
      cur.contents = match[1];
      return {
        value: Primitive_option.some(match[0]),
        done: false
      };
    } else {
      return {
        value: undefined,
        done: true
      };
    }
  };
  return {
    next: next
  };
}

export {
  make,
  size,
  isEmpty,
  enqueue,
  peek,
  peekExn,
  dequeue,
  dequeueExn,
  toArray,
  fromArray,
  forEach,
  reduce,
  map,
  filter,
  iterator,
}
/* No side effect */
