// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as PersistentHashMap from "./PersistentHashMap.res.mjs";

function make() {
  return PersistentHashMap.make();
}

let size = PersistentHashMap.size;

let has = PersistentHashMap.has;

function add(s, x) {
  return PersistentHashMap.set(s, x, undefined);
}

let remove = PersistentHashMap.remove;

function fromArray(arr) {
  let s = {
    contents: PersistentHashMap.make()
  };
  arr.forEach(x => {
    s.contents = PersistentHashMap.set(s.contents, x, undefined);
  });
  return s.contents;
}

let toArray = PersistentHashMap.keys;

function forEach(s, f) {
  PersistentHashMap.forEach(s, (k, param) => f(k));
}

function reduce(s, init, f) {
  return PersistentHashMap.reduce(s, init, (acc, k, param) => f(acc, k));
}

let union = PersistentHashMap.merge;

function intersect(a, b) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(a, (k, param) => {
      if (PersistentHashMap.has(b, k)) {
        PersistentHashMap.setMut(t, k, undefined);
        return;
      }
    });
    return t;
  });
}

function difference(a, b) {
  return PersistentHashMap.withTransient(PersistentHashMap.make(), t => {
    PersistentHashMap.forEach(a, (k, param) => {
      if (!PersistentHashMap.has(b, k)) {
        PersistentHashMap.setMut(t, k, undefined);
        return;
      }
    });
    return t;
  });
}

function iterator(s) {
  let buffer = PersistentHashMap.keys(s);
  let len = buffer.length;
  let i = {
    contents: 0
  };
  let next = () => {
    if (i.contents >= len) {
      return {
        value: undefined,
        done: true
      };
    }
    let x = buffer[i.contents];
    i.contents = i.contents + 1 | 0;
    return {
      value: Primitive_option.some(x),
      done: false
    };
  };
  return {
    next: next
  };
}

let asTransient = PersistentHashMap.asTransient;

function addMut(t, x) {
  return PersistentHashMap.setMut(t, x, undefined);
}

let removeMut = PersistentHashMap.removeMut;

function hasMut(t, x) {
  return PersistentHashMap.getMut(t, x) !== undefined;
}

let persistent = PersistentHashMap.persistent;

function withTransient(s, f) {
  return PersistentHashMap.persistent(f(PersistentHashMap.asTransient(s)));
}

export {
  make,
  size,
  has,
  add,
  remove,
  fromArray,
  toArray,
  forEach,
  reduce,
  union,
  intersect,
  difference,
  iterator,
  asTransient,
  addMut,
  removeMut,
  hasMut,
  persistent,
  withTransient,
}
/* PersistentHashMap Not a pure module */
